export const PROFESSIONS = {
  merchant: {
    name: 'Merchant',
    description: 'More starting cash and better prices, but no special medical or repair training.',
    money: 350,
    medicine: 0,
    parts: 0,
    reputation: 8,
  },
  physician: {
    name: 'Physician',
    description: 'Treats illness more effectively and begins with extra medicine.',
    money: 80,
    medicine: 10,
    parts: 0,
    reputation: 4,
  },
  engineer: {
    name: 'Engineer',
    description: 'Repairs wagons, pumps, and machinery with fewer spare parts.',
    money: 120,
    medicine: 0,
    parts: 8,
    reputation: 3,
  },
  scout: {
    name: 'Scout',
    description: 'Travels faster, hunts more efficiently, and reads dangerous country well.',
    money: 60,
    medicine: 2,
    parts: 2,
    reputation: 5,
  },
};

const commonParty = [
  {
    name: 'Clara Finch',
    role: 'Nurse and teacher',
    bio: 'Clara has treated dockworkers, children, and sailors in Boston. She keeps careful notes and refuses to abandon anyone who can still be helped.',
  },
  {
    name: 'Elias Reed',
    role: 'Blacksmith and mechanic',
    bio: 'Elias can straighten an axle with a hammer, mend a boiler fitting, or argue for an hour about the proper temper of steel.',
  },
  {
    name: 'Isaiah Bell',
    role: 'Surveyor and hunter',
    bio: 'A veteran sailor and practiced marksman, Isaiah reads weather in the clouds and distance in the shape of the land.',
  },
  {
    name: 'Nora Whitcomb',
    role: 'Bookkeeper and journalist',
    bio: 'Nora carries ledgers, pencils, and a stubborn belief that fortunes are built by people who know exactly what they owe.',
  },
];

export const CAMPAIGNS = {
  gold: {
    id: 'gold',
    title: 'The Golden Fortune',
    year: 1849,
    destination: 'The California gold fields',
    tagline: 'Cross a continent before winter closes the Sierra Nevada.',
    startDate: '1849-04-10T12:00:00',
    startingMoney: 1450,
    vehicle: 'canvas-topped emigrant wagon',
    intro: [
      'Boston, April 1849. News of gold at Sutter’s Mill has emptied counting houses, workshops, and harbor taverns. Ships sail around Cape Horn, but your company has chosen the longer gamble: west by canal, river, road, and wagon until the continent itself runs out.',
      'Your contract is simple only on paper. Reach California with enough people, tools, and capital to claim ground or build a business. The journey will cross crowded river towns, cholera camps, the Platte valley, South Pass, the Humboldt country, the Forty Mile Desert, and the Sierra Nevada before snow seals the passes.',
    ],
    victoryTitle: 'A Fortune at the End of the Trail',
    party: commonParty,
    route: [
      {
        name: 'Boston, Massachusetts',
        region: 'newEngland',
        distance: 0,
        mode: 'road',
        store: true,
        river: null,
        story: 'The company gathers near the harbor beneath a cold salt wind. Crates of flour, medicine, iron fittings, rifles, and ledgers crowd the yard. Families watch from the street as though the expedition were already a funeral procession.',
      },
      {
        name: 'Albany and the Hudson River',
        region: 'newEngland',
        distance: 170,
        mode: 'road',
        store: true,
        river: { name: 'Hudson River', difficulty: 24 },
        story: 'Albany rises above the Hudson in brick, smoke, and steeples. Canal agents shout prices while packet boats crowd the basin. The Erie Canal offers speed, but every delay costs money and every crowded lodging house carries illness.',
      },
      {
        name: 'Buffalo and Lake Erie',
        region: 'greatLakes',
        distance: 360,
        mode: 'canal',
        store: true,
        river: null,
        story: 'After weeks beside the Erie Canal, Buffalo feels like the western edge of the settled world. Lake Erie is steel gray beneath hard wind. Warehouses are packed with emigrants buying tools they do not know how to use.',
      },
      {
        name: 'Cleveland, Ohio',
        region: 'greatLakes',
        distance: 190,
        mode: 'lake',
        store: true,
        river: { name: 'Cuyahoga River', difficulty: 20 },
        story: 'Cleveland’s harbor is muddy, loud, and growing by the month. Grain elevators and foundries promise that industry is following the frontier west. Elias spends an evening examining wagon iron and pronounces half of it decorative rubbish.',
      },
      {
        name: 'Cincinnati and the Ohio River',
        region: 'ohioValley',
        distance: 255,
        mode: 'road',
        store: true,
        river: { name: 'Ohio River', difficulty: 42 },
        story: 'The Ohio River carries flatboats, steamers, livestock, timber, and every rumor in the republic. The city smells of smoke, animals, wet rope, and industry. Passage west can be purchased here, but not certainty.',
      },
      {
        name: 'St. Louis and the Mississippi',
        region: 'mississippi',
        distance: 345,
        mode: 'steamer',
        store: true,
        river: { name: 'Mississippi River', difficulty: 50 },
        story: 'St. Louis is a vast outfitting camp disguised as a city. Steamboats whistle at the levee. Cholera notices appear on doors. Beyond the Missouri River, merchants say, the road belongs to weather, distance, and luck.',
      },
      {
        name: 'Independence, Missouri',
        region: 'missouri',
        distance: 250,
        mode: 'road',
        store: true,
        river: { name: 'Missouri River', difficulty: 46 },
        story: 'Independence is churned into mud by wagons, oxen, horses, and thousands of boots. Here the company exchanges eastern convenience for an overland wagon train. Every pound must justify itself. Every animal must survive nearly two thousand miles.',
      },
      {
        name: 'Fort Kearny and the Platte River',
        region: 'plains',
        distance: 315,
        mode: 'wagon',
        store: true,
        river: { name: 'Platte River', difficulty: 34 },
        story: 'The Platte is broad, shallow, braided, and deceptive. Its valley is crowded with wagons moving west and graves marking those who will not. Fort Kearny offers mail, repairs, and news of cholera farther up the trail.',
      },
      {
        name: 'Chimney Rock',
        region: 'plains',
        distance: 275,
        mode: 'wagon',
        store: false,
        river: { name: 'North Platte River', difficulty: 38 },
        story: 'Chimney Rock rises above the prairie like a monument built for travelers. The party can see it for days. At night, wolves call beyond the fire and the sky seems larger than the entire Atlantic coast.',
      },
      {
        name: 'Fort Laramie',
        region: 'plains',
        distance: 95,
        mode: 'wagon',
        store: true,
        river: { name: 'Laramie River', difficulty: 31 },
        story: 'At Fort Laramie, soldiers, traders, emigrants, and Native families meet in uneasy commerce. Prices are high, but the mountains ahead punish weak equipment. Nora hears that early snow has lingered in the high country.',
      },
      {
        name: 'Independence Rock and the Sweetwater',
        region: 'rockies',
        distance: 310,
        mode: 'wagon',
        store: false,
        river: { name: 'Sweetwater River', difficulty: 36 },
        story: 'Names carved into Independence Rock turn the landmark into a stone ledger of ambition. The Sweetwater winds through harsher country. Animals tire quickly, nights sharpen, and every broken wheel costs precious daylight.',
      },
      {
        name: 'South Pass',
        region: 'rockies',
        distance: 115,
        mode: 'wagon',
        store: false,
        river: null,
        story: 'South Pass is not the dramatic wall the company imagined. It is a broad, windswept saddle where the continent quietly divides. The gradual crossing makes wagon travel possible, but the Pacific slope offers no mercy merely because the summit was gentle.',
      },
      {
        name: 'Fort Bridger',
        region: 'rockies',
        distance: 125,
        mode: 'wagon',
        store: true,
        river: { name: 'Green River', difficulty: 48 },
        story: 'Fort Bridger is a rough trading post of cabins, corrals, smoke, and argument. Guides debate the established trail and the infamous Hastings Cutoff. The so-called shortcut has already earned a reputation for thirst and delay.',
        decision: {
          title: 'The Cutoff Debate',
          text: 'A promoter insists the Hastings Cutoff will save time. A Shoshone trader quietly says the salt desert is wider than the promoters admit. Which road will the company take?',
          choices: [
            {
              label: 'Remain on the established California Trail',
              result: 'You accept a longer but better-known route, gaining reliable water information from experienced travelers.',
              effects: { days: 3, reputation: 4, risk: -0.08 },
              flag: 'mainTrail',
            },
            {
              label: 'Take the Hastings Cutoff',
              result: 'The company turns southwest toward the Great Salt Lake. The road is uncertain and the salt desert will demand extra water.',
              effects: { morale: 4, water: -18, risk: 0.2 },
              flag: 'hastings',
            },
          ],
        },
      },
      {
        name: 'Salt Lake Valley',
        region: 'basin',
        distance: 120,
        mode: 'wagon',
        store: true,
        river: null,
        story: 'The young settlement in the Salt Lake Valley is busy with fields, workshops, and new construction. Supplies can be purchased, but the desert west of the lake has ruined stronger companies than yours.',
      },
      {
        name: 'Humboldt Wells',
        region: 'desert',
        distance: 410,
        mode: 'wagon',
        store: false,
        river: { name: 'Humboldt River', difficulty: 26 },
        story: 'The Humboldt River is less a promise than a guide through sage and alkali country. Water may be muddy or foul, grass scarce, and abandoned property common. Every mile west reveals another decision someone regretted.',
      },
      {
        name: 'Forty Mile Desert',
        region: 'desert',
        distance: 165,
        mode: 'wagon',
        store: false,
        river: null,
        story: 'The Forty Mile Desert begins in heat, dust, and the smell of exhausted animals. Travelers move at night to spare their teams. Broken wagons and bones line the route toward the Truckee River.',
      },
      {
        name: 'Truckee River',
        region: 'sierra',
        distance: 95,
        mode: 'wagon',
        store: false,
        river: { name: 'Truckee River', difficulty: 44 },
        story: 'Cold water and pine trees return along the Truckee River, but relief is temporary. Granite walls rise ahead. The Sierra crossing will decide whether the company reaches California as owners, laborers, or names in someone else’s diary.',
        decision: {
          title: 'Choose a Sierra Crossing',
          text: 'Travelers describe two practical approaches: the Truckee route toward Emigrant Gap or the Carson route farther south. Both may receive early snow.',
          choices: [
            {
              label: 'Take the Truckee route',
              result: 'The company follows the river toward the steep pass and heavily traveled wagon road.',
              effects: { days: 1, risk: 0.05 },
              flag: 'truckee',
            },
            {
              label: 'Turn toward the Carson route',
              result: 'You trade distance for a route believed to offer more forage and alternate approaches.',
              effects: { days: 4, food: -18, risk: -0.03 },
              flag: 'carson',
            },
          ],
        },
      },
      {
        name: 'Sierra Nevada Pass',
        region: 'sierra',
        distance: 80,
        mode: 'mountain',
        store: false,
        river: null,
        story: 'The wagons climb through pine forest, granite, cold streams, and narrow grades. Chains hold wheels on descents. Every cloud is examined for snow. The company can almost smell the warm valley beyond the ridge.',
      },
      {
        name: 'Sacramento and Sutter’s Fort',
        region: 'california',
        distance: 105,
        mode: 'wagon',
        store: true,
        river: { name: 'Sacramento River', difficulty: 36 },
        story: 'Sacramento is a city being invented in mud. Tents, stores, saloons, workshops, and offices spread along the river. Gold dust changes hands by weight. The mountains are full of claims, but fortunes are also being made selling tools and food to people who still believe wealth is one pan away.',
      },
      {
        name: 'Coloma and the American River',
        region: 'california',
        distance: 45,
        mode: 'wagon',
        store: false,
        river: { name: 'American River', difficulty: 30 },
        story: 'The American River flashes through the foothills below Coloma. The company has crossed the continent. Now comes the final gamble: dig for gold, purchase a claim, or sell necessity to the thousands who arrived with dreams but little preparation.',
      },
    ],
  },
  oil: {
    id: 'oil',
    title: 'The Black Gold Empire',
    year: 1901,
    destination: 'Spindletop and the Texas oil fields',
    tagline: 'Follow the gusher south and turn a frontier boom into an industry.',
    startDate: '1901-01-24T12:00:00',
    startingMoney: 1750,
    vehicle: 'freight wagon with rail and steamer passage',
    intro: [
      'Boston, January 1901. Two weeks ago, a well near Beaumont, Texas, erupted with such force that newspapers call it a new age of petroleum. Investors, drillers, merchants, engineers, and outright gamblers are already moving toward the Gulf Coast.',
      'This is not the frontier of 1849. Rails cross much of the nation, telegraph wires carry rumors faster than horses, and steam power moves freight. Yet beyond the depots and river ports, mud, disease, weather, broken machinery, and bad contracts can still destroy a company before it drills a foot.',
    ],
    victoryTitle: 'The First Well of an Empire',
    party: commonParty,
    route: [
      {
        name: 'Boston, Massachusetts',
        region: 'newEngland',
        distance: 0,
        mode: 'road',
        store: true,
        river: null,
        story: 'The expedition leaves Boston beneath telegraph wires and winter smoke. Crates contain steel fittings, drilling cable, medicine, ledgers, preserved food, and enough personal ambition to power a locomotive.',
      },
      {
        name: 'Albany and the Hudson River',
        region: 'newEngland',
        distance: 170,
        mode: 'rail',
        store: true,
        river: { name: 'Hudson River', difficulty: 20 },
        story: 'Ice rims the Hudson while freight agents compete for cargo. The rail system is fast, but winter delays and damaged bridges can immobilize an expedition as effectively as a broken wagon axle.',
      },
      {
        name: 'Buffalo, New York',
        region: 'greatLakes',
        distance: 290,
        mode: 'rail',
        store: true,
        river: null,
        story: 'Buffalo is a city of grain, coal, steel, and lake wind. Elias studies drilling catalogs in a hotel lobby while Nora discovers that every second salesman claims to own a Texas lease.',
      },
      {
        name: 'Cleveland, Ohio',
        region: 'greatLakes',
        distance: 190,
        mode: 'rail',
        store: true,
        river: { name: 'Cuyahoga River', difficulty: 16 },
        story: 'Cleveland’s refineries and machine shops offer a glimpse of what petroleum can become. The company may purchase better equipment here, but every dollar spent on machinery is a dollar not spent on land.',
      },
      {
        name: 'Cincinnati and the Ohio River',
        region: 'ohioValley',
        distance: 255,
        mode: 'rail',
        store: true,
        river: { name: 'Ohio River', difficulty: 34 },
        story: 'Cincinnati is wet with winter rain and crowded with southbound freight. The Ohio River offers steamer passage toward the Mississippi, while rail lines promise speed at a higher price.',
        decision: {
          title: 'Rail or River?',
          text: 'A steamer captain offers cheap freight passage to Memphis. A rail agent promises a faster connection but demands payment in advance.',
          choices: [
            {
              label: 'Book the river steamer',
              result: 'The company saves money but accepts the hazards of winter river travel and crowded decks.',
              effects: { money: 140, days: 3, risk: 0.08 },
              flag: 'steamerSouth',
            },
            {
              label: 'Pay for the railway connection',
              result: 'The expedition moves faster and keeps delicate equipment away from river spray.',
              effects: { money: -180, days: -2, risk: -0.05 },
              flag: 'railSouth',
            },
          ],
        },
      },
      {
        name: 'Louisville, Kentucky',
        region: 'ohioValley',
        distance: 105,
        mode: 'rail',
        store: true,
        river: { name: 'Ohio River', difficulty: 32 },
        story: 'Louisville’s falls once forced every river traveler to stop. Now canals, rails, and warehouses surround the crossing. The company hears reports of flooded roads farther south.',
      },
      {
        name: 'Memphis and the Mississippi',
        region: 'mississippi',
        distance: 385,
        mode: 'rail',
        store: true,
        river: { name: 'Mississippi River', difficulty: 48 },
        story: 'Memphis stands above a broad brown river carrying timber, cotton, machinery, and migrants. Mosquitoes are not yet at summer strength, but damp quarters and crowded travel still spread fever and pneumonia.',
      },
      {
        name: 'Little Rock and the Arkansas River',
        region: 'arkansas',
        distance: 140,
        mode: 'road',
        store: true,
        river: { name: 'Arkansas River', difficulty: 38 },
        story: 'The road west from the Mississippi climbs through forest and river country. Little Rock offers repairs and information from men who have already returned from Texas after losing money to false leases.',
      },
      {
        name: 'Texarkana and the Red River Country',
        region: 'texasNorth',
        distance: 145,
        mode: 'rail',
        store: true,
        river: { name: 'Red River', difficulty: 40 },
        story: 'At Texarkana, the expedition crosses into Texas beneath cold rain and a sky that seems to stretch to Mexico. Freight yards are full of lumber, pipe, cattle, and drilling equipment bound south.',
      },
      {
        name: 'Dallas and the Trinity River',
        region: 'texasNorth',
        distance: 195,
        mode: 'rail',
        store: true,
        river: { name: 'Trinity River', difficulty: 36 },
        story: 'Dallas is already a commercial center, more city than frontier post. Investors gather in hotel lobbies with maps, newspapers, and contracts. Rumors say Spindletop land prices double by the hour.',
        decision: {
          title: 'A Corsicana Detour',
          text: 'Corsicana’s field has produced commercial oil since the 1890s. A broker offers a stable lease there. The greater gamble lies farther southeast at Beaumont.',
          choices: [
            {
              label: 'Inspect Corsicana before continuing',
              result: 'The detour teaches the company how established Texas fields operate and earns useful contacts, but costs time.',
              effects: { days: 5, money: -80, reputation: 12, risk: -0.05 },
              flag: 'corsicana',
            },
            {
              label: 'Race directly toward Beaumont',
              result: 'You preserve time and cash while accepting poorer information and a more speculative market.',
              effects: { morale: 5, risk: 0.08 },
              flag: 'beaumontRush',
            },
          ],
        },
      },
      {
        name: 'Corsicana and the first Texas oil field',
        region: 'texasNorth',
        distance: 60,
        mode: 'road',
        store: true,
        river: null,
        story: 'Corsicana discovered oil while drilling for water in 1894. Derricks and storage tanks show what disciplined production looks like. The lesson is clear: finding oil is only the first step. Moving, refining, financing, and selling it create the empire.',
      },
      {
        name: 'Waco and the Brazos River',
        region: 'texasCentral',
        distance: 105,
        mode: 'road',
        store: true,
        river: { name: 'Brazos River', difficulty: 43 },
        story: 'The Brazos runs high after rain. Waco’s bridge, stores, and rail connections make it a natural stop. Southbound travelers warn of mud deep enough to swallow freight wheels.',
      },
      {
        name: 'Austin and the Colorado River',
        region: 'texasCentral',
        distance: 105,
        mode: 'road',
        store: true,
        river: { name: 'Colorado River', difficulty: 41 },
        story: 'Austin’s limestone hills, government offices, and river crossings offer a final chance to secure documents and legal advice. Nora discovers that a clear title may be worth more than a promising geological report.',
      },
      {
        name: 'Houston and Buffalo Bayou',
        region: 'texasGulf',
        distance: 165,
        mode: 'rail',
        store: true,
        river: { name: 'Buffalo Bayou', difficulty: 28 },
        story: 'Houston is rebuilding trade after the catastrophic Galveston hurricane of 1900. Rail yards and bayou warehouses point toward the industrial future. Oil men are already discussing refineries and pipelines before most wells exist.',
      },
      {
        name: 'Liberty and the Trinity lowlands',
        region: 'texasGulf',
        distance: 45,
        mode: 'road',
        store: false,
        river: { name: 'Lower Trinity River', difficulty: 46 },
        story: 'The Gulf plain is wet, flat, and thick with timber, mosquitoes, and mud. Wagons sink to their hubs. Warm air carries the smell of marsh and pine. Beaumont lies only days away, but damaged machinery here may never arrive in time.',
      },
      {
        name: 'Beaumont and the Neches River',
        region: 'texasGulf',
        distance: 55,
        mode: 'road',
        store: true,
        river: { name: 'Neches River', difficulty: 38 },
        story: 'Beaumont is overwhelmed. Hotels, boarding houses, warehouses, and streets spill over with speculators and workers. Wagons carry pipe toward the low hill called Spindletop. Every conversation begins with oil and ends with money.',
      },
      {
        name: 'Spindletop',
        region: 'texasGulf',
        distance: 6,
        mode: 'road',
        store: false,
        river: null,
        story: 'Derricks crowd the rise south of Beaumont. Mud, steam, oil spray, lumber, boilers, and shouting men cover the field. The Lucas gusher has changed Texas. Your company has arrived early enough to build something—but not early enough to avoid rivals, bad land, and dangerous wells.',
      },
    ],
  },
};

export const REGION_INFO = {
  newEngland: { label: 'New England', baseWeather: 'Cold wind and variable skies', forage: 0.7, hunt: ['deer', 'rabbit', 'wild turkey'] },
  greatLakes: { label: 'Great Lakes', baseWeather: 'Lake wind and sudden squalls', forage: 0.65, hunt: ['deer', 'waterfowl', 'rabbit'] },
  ohioValley: { label: 'Ohio Valley', baseWeather: 'Rain, humidity, and thunderstorms', forage: 0.8, hunt: ['deer', 'wild turkey', 'squirrel'] },
  mississippi: { label: 'Mississippi Valley', baseWeather: 'Damp air, river fog, and heavy rain', forage: 0.85, hunt: ['deer', 'waterfowl', 'wild hog'] },
  missouri: { label: 'Missouri Border', baseWeather: 'Warm wind and muddy roads', forage: 0.8, hunt: ['deer', 'turkey', 'rabbit'] },
  plains: { label: 'Great Plains', baseWeather: 'Open wind and fast-moving storms', forage: 0.75, hunt: ['bison', 'pronghorn', 'prairie chicken'] },
  rockies: { label: 'Rocky Mountains', baseWeather: 'Cold nights and mountain storms', forage: 0.45, hunt: ['elk', 'mule deer', 'bighorn sheep'] },
  basin: { label: 'Great Basin', baseWeather: 'Dry wind and cold nights', forage: 0.35, hunt: ['jackrabbit', 'pronghorn', 'sage grouse'] },
  desert: { label: 'Humboldt and Desert Country', baseWeather: 'Heat, alkali dust, and scarce water', forage: 0.15, hunt: ['jackrabbit', 'sage grouse', 'pronghorn'] },
  sierra: { label: 'Sierra Nevada', baseWeather: 'Cold rain, snow, and steep grades', forage: 0.45, hunt: ['black-tailed deer', 'black bear', 'grouse'] },
  california: { label: 'California Foothills', baseWeather: 'Warm days and cool river nights', forage: 0.75, hunt: ['deer', 'rabbit', 'quail'] },
  arkansas: { label: 'Arkansas River Country', baseWeather: 'Rain, forest humidity, and muddy roads', forage: 0.85, hunt: ['deer', 'wild turkey', 'black bear'] },
  texasNorth: { label: 'North Texas', baseWeather: 'Prairie wind, thunderstorms, and blue northers', forage: 0.75, hunt: ['white-tailed deer', 'turkey', 'quail'] },
  texasCentral: { label: 'Central Texas', baseWeather: 'Warm sun, sudden storms, and limestone dust', forage: 0.65, hunt: ['white-tailed deer', 'wild turkey', 'feral hog'] },
  texasGulf: { label: 'Texas Gulf Plain', baseWeather: 'Humidity, Gulf rain, heat, and mosquitoes', forage: 0.7, hunt: ['waterfowl', 'wild hog', 'alligator'] },
};

export const RANDOM_EVENTS = [
  { id:'cold-rain', regions:['newEngland','greatLakes','ohioValley'], title:'Cold Rain and Deep Mud', text:'A day of cold rain turns the road into ruts and brown water. Animals strain while boots and clothing remain wet.', choices:[
    {label:'Make a dry camp',result:'You lose a day drying equipment, but the party avoids the worst exposure.',effects:{days:1,food:-8,morale:1}},
    {label:'Push through the mud',result:'The company makes distance, but the wagon and animals pay for it.',effects:{miles:10,wagon:-7,animals:-3,riskRoll:'injury'}}]},
  { id:'lake-squall', regions:['greatLakes'], title:'Lake Squall', text:'A fast squall lashes the lake and harbor with hard wind. Cargo shifts beneath wet canvas.', choices:[
    {label:'Secure every crate',result:'Elias spends hours lashing equipment. Nothing is lost.',effects:{days:1,parts:-1,reputation:2}},
    {label:'Trust the freight crew',result:'The company saves time, but one crate arrives damaged.',effects:{money:-45,parts:-2,morale:-2}}]},
  { id:'river-fog', regions:['ohioValley','mississippi','arkansas','texasGulf'], title:'River Fog', text:'Dense fog swallows the river, shoreline, and every familiar landmark. Bells and whistles sound somewhere beyond sight.', choices:[
    {label:'Wait for clear visibility',result:'The fog lifts near noon. The delay costs food but no equipment.',effects:{days:1,food:-6}},
    {label:'Move carefully by sound',result:'The company gains time but strikes submerged debris.',effects:{miles:8,wagon:-6,parts:-1}}]},
  { id:'cholera-camp', regions:['missouri','plains'], title:'Cholera in the Camps', text:'A crowded emigrant camp ahead has several sudden deaths. The water source is shared by people and livestock.', choices:[
    {label:'Detour and boil water',result:'The detour is slow, but Clara keeps the company away from the contaminated camp.',effects:{days:2,food:-10,water:-8,reputation:3}},
    {label:'Resupply quickly and leave',result:'You gain water and time, but illness may already be traveling with the company.',effects:{water:20,diseaseRoll:'cholera',risk:.08}}]},
  { id:'plains-thunderstorm', regions:['plains','texasNorth','texasCentral'], title:'Violent Thunderstorm', text:'A black wall of cloud rolls across the open country. Lightning strikes close enough to smell, and hail rattles on canvas.', choices:[
    {label:'Circle the wagons and shelter',result:'The company waits out the storm with frightened animals and little damage.',effects:{days:1,morale:-1,food:-5}},
    {label:'Race for lower ground',result:'The animals run hard. The company escapes the hail core but risks a rollover.',effects:{miles:12,animals:-4,riskRoll:'wagon'}}]},
  { id:'prairie-fire', regions:['plains','texasNorth','texasCentral'], title:'Prairie Fire', text:'Smoke appears along the horizon and the wind drives a line of flame through dry grass toward the road.', choices:[
    {label:'Burn a firebreak',result:'The company burns a strip of grass and shelters in the blackened ground as the fire passes.',effects:{water:-12,morale:3,reputation:2}},
    {label:'Run for the river',result:'The animals are driven hard, and some supplies are abandoned to save the wagon.',effects:{miles:18,food:-18,parts:-2,animals:-5}}]},
  { id:'bison-herd', regions:['plains'], title:'A Vast Bison Herd', text:'Bison cover the prairie from one horizon to the other. The ground trembles as the herd crosses the road.', choices:[
    {label:'Wait and observe',result:'Isaiah studies the herd and finds a safe route after it passes.',effects:{days:1,morale:5}},
    {label:'Hunt at the edge of the herd',result:'The hunt yields meat, but ammunition and time are spent.',effects:{food:70,ammo:-7,days:1,reputation:-1}}]},
  { id:'trading-camp', regions:['plains','rockies','basin'], title:'A Trading Camp', text:'A small camp of Native traders offers dried food, moccasins, and information about water and weather ahead.', choices:[
    {label:'Trade fairly and listen',result:'The company buys provisions and receives reliable information about the next water source.',effects:{money:-55,food:30,water:18,reputation:8,risk:-.06}},
    {label:'Decline and continue',result:'You conserve money but leave without local knowledge.',effects:{morale:-1}}]},
  { id:'mountain-snow', regions:['rockies','sierra'], title:'Mountain Snow', text:'Snow begins before dawn and hides the road beneath a white sheet. The temperature falls throughout the day.', choices:[
    {label:'Build shelter and wait',result:'The party remains warm but consumes scarce food and fuel.',effects:{days:2,food:-14,morale:-2}},
    {label:'Keep moving below the ridge',result:'The company gains ground, but cold and poor footing cause injuries.',effects:{miles:10,partyDamage:6,diseaseRoll:'pneumonia'}}]},
  { id:'broken-axle', regions:['plains','rockies','basin','desert','sierra','texasNorth','texasCentral','texasGulf'], title:'Broken Axle', text:'A wheel drops into a rut with a crack. The wagon leans sharply, and one axle is split near the hub.', choices:[
    {label:'Repair it properly',result:'Elias replaces and braces the damaged section.',effects:{days:1,parts:-3,wagon:10}},
    {label:'Lash it and continue',result:'The temporary repair saves parts but weakens the wagon.',effects:{wagon:-12,risk:.08}}]},
  { id:'desert-water', regions:['desert','basin'], title:'The Water Barrels Run Low', text:'Heat, leaking staves, and greater-than-expected distance leave the company with less water than planned.', choices:[
    {label:'Travel through the night',result:'Cooler temperatures preserve water, but fatigue lowers morale.',effects:{miles:22,days:1,water:-10,morale:-5,partyDamage:2}},
    {label:'Search for a spring',result:'Isaiah finds muddy water after a long search. It must be boiled before use.',effects:{days:2,water:30,food:-9,diseaseRoll:'dysentery'}}]},
  { id:'rattlesnake', regions:['plains','basin','desert','texasNorth','texasCentral'], title:'Rattlesnake in the Bedrolls', text:'A rattlesnake coils beneath a folded blanket as camp is broken at dawn.', choices:[
    {label:'Let Isaiah remove it',result:'The snake is carried beyond camp without injury.',effects:{morale:1}},
    {label:'Kill it quickly',result:'The danger ends, but a frightened animal tears loose from its tether.',effects:{animals:-3,ammo:-1}}]},
  { id:'bear-camp', regions:['rockies','sierra','arkansas'], title:'Bear in Camp', text:'A bear enters camp after dark, drawn by food and grease. Pots scatter while the animals panic.', choices:[
    {label:'Drive it off with noise',result:'The bear retreats after a deafening display of pans, shouts, and firewood.',effects:{food:-12,morale:2}},
    {label:'Shoot before it reaches supplies',result:'The shot saves food but risks injury in the darkness.',effects:{ammo:-2,food:20,riskRoll:'injury'}}]},
  { id:'blue-norther', regions:['texasNorth','texasCentral'], title:'A Blue Norther', text:'Warm air vanishes beneath a violent northern wind. The temperature falls with shocking speed, catching the company in light clothing.', choices:[
    {label:'Stop and build windbreaks',result:'Canvas and freight create shelter until the cold front passes.',effects:{days:1,food:-7,parts:-1}},
    {label:'Push toward the next town',result:'The company gains distance but several travelers suffer from exposure.',effects:{miles:15,partyDamage:7,diseaseRoll:'pneumonia'}}]},
  { id:'gulf-flood', regions:['texasGulf','mississippi'], title:'Flooded Lowlands', text:'Heavy rain raises creeks across the road. Water spreads through timber and pasture until the route disappears.', choices:[
    {label:'Wait on high ground',result:'The flood begins falling after two days.',effects:{days:2,food:-14,morale:-2}},
    {label:'Hire a local guide',result:'A guide leads the company along a raised route through the flooded country.',effects:{money:-70,days:1,reputation:4,risk:-.04}}]},
  { id:'mosquito-fever', regions:['mississippi','arkansas','texasGulf'], title:'Mosquitoes and Fever', text:'Warm, wet evenings bring clouds of mosquitoes. One party member wakes shaking with fever.', choices:[
    {label:'Rest and treat the fever',result:'Clara uses medicine and keeps the patient hydrated.',effects:{days:2,medicine:-2,partyHeal:6,clearDiseaseChance:.6}},
    {label:'Continue at a slower pace',result:'The company preserves time, but the fever may worsen.',effects:{miles:8,diseaseRoll:'malaria',partyDamage:5}}]},
  { id:'washed-bridge', regions:['newEngland','greatLakes','ohioValley','arkansas','texasNorth'], title:'Washed-Out Bridge', text:'Floodwater has removed part of a bridge and stranded freight on both approaches.', choices:[
    {label:'Help rebuild the crossing',result:'The company contributes labor and parts. Local freight agents remember the favor.',effects:{days:2,parts:-2,reputation:10}},
    {label:'Pay for a detour',result:'A teamster leads the expedition to another crossing.',effects:{money:-65,days:1}}]},
  { id:'contract-offer', regions:['greatLakes','ohioValley','mississippi','texasNorth','texasCentral','texasGulf','california'], title:'A Risky Contract', text:'A merchant offers payment to carry a heavy crate to the next major settlement. The contents are legal, he insists, but fragile.', choices:[
    {label:'Accept the freight',result:'The cargo slows the company but earns cash and a business contact.',effects:{money:95,miles:-5,wagon:-3,reputation:3}},
    {label:'Refuse the burden',result:'The company keeps its schedule and cargo space.',effects:{morale:1}}]},
  { id:'lost-child', regions:['missouri','plains','rockies','texasNorth','texasCentral'], title:'A Child Missing from Another Company', text:'A nearby party discovers that a child wandered away while animals were being gathered. Light is fading.', choices:[
    {label:'Join the search',result:'Isaiah finds tracks near a creek. The child is returned after midnight.',effects:{days:1,morale:8,reputation:12,food:-5}},
    {label:'Continue before dark',result:'Your company keeps moving, but no one speaks much that evening.',effects:{morale:-10,reputation:-8,miles:8}}]},
  { id:'prairie-game', regions:['plains','texasNorth'], title:'Pronghorn on the Ridge', text:'A small herd of pronghorn watches from a distant rise. Isaiah believes one careful stalk could replenish meat.', choices:[
    {label:'Spend the afternoon hunting',result:'The hunt is successful and the company preserves the meat.',effects:{days:1,ammo:-4,food:45,morale:3}},
    {label:'Keep the schedule',result:'The herd disappears into the open country as the wagon moves on.',effects:{miles:10}}]},
];

export const DISEASES = {
  dysentery: { name:'dysentery', severity:7, duration:5, text:'Contaminated water causes severe intestinal illness and dangerous dehydration.' },
  cholera: { name:'cholera', severity:12, duration:4, text:'A sudden, severe waterborne illness spreads through the camp.' },
  typhoid: { name:'typhoid fever', severity:8, duration:7, text:'A sustained fever and weakness leave the patient unable to work.' },
  pneumonia: { name:'pneumonia', severity:9, duration:6, text:'Cold exposure develops into coughing, fever, and difficult breathing.' },
  malaria: { name:'malarial fever', severity:7, duration:7, text:'Repeated chills and fever weaken the patient in the warm lowlands.' },
  measles: { name:'measles', severity:6, duration:6, text:'A contagious fever and rash spread through crowded travel quarters.' },
  heat: { name:'heat exhaustion', severity:6, duration:3, text:'Heat and dehydration leave the traveler weak and confused.' },
};

export const SUPPLY_PACKAGES = {
  lean: { name:'Lean Expedition', cost:540, description:'Fast and inexpensive, with little margin for delay.', supplies:{food:260,water:120,medicine:8,parts:9,ammo:38,animals:72,wagon:86} },
  balanced: { name:'Balanced Outfit', cost:820, description:'Enough food, medicine, animals, and repair stock for a careful journey.', supplies:{food:430,water:180,medicine:15,parts:16,ammo:58,animals:88,wagon:94} },
  prepared: { name:'Prepared Company', cost:1120, description:'Heavy reserves and strong equipment at the cost of working capital.', supplies:{food:600,water:250,medicine:24,parts:25,ammo:82,animals:100,wagon:100} },
};
