import Phaser from 'phaser';
import './style.css';

type Upgrade='power'|'speed'|'value'|'scoop';
type Save={coins:number;earned:number;power:number;speed:number;value:number;scoop:number;unlocked:number;current:number;cleared:number[]};
type Level={name:string;count:number;unlock:number;rockValue:number;goldChance:number;crystalChance:number;ground:number;wall:number};
const LEVELS:Level[]=[
{name:'Gravel Pit',count:10,unlock:0,rockValue:5,goldChance:0,crystalChance:0,ground:0x8a5b32,wall:0x51351f},
{name:'Granite Cut',count:14,unlock:50,rockValue:11,goldChance:.12,crystalChance:0,ground:0x686765,wall:0x3f4245},
{name:'Gold Ridge',count:18,unlock:400,rockValue:22,goldChance:.30,crystalChance:.03,ground:0x81552d,wall:0x56361e},
{name:'Crystal Basin',count:22,unlock:1100,rockValue:45,goldChance:.20,crystalChance:.30,ground:0x466f77,wall:0x29444d}
];
const KEY='mine-dozer-save-v2';
const defaults:Save={coins:0,earned:0,power:1,speed:1,value:1,scoop:1,unlocked:0,current:0,cleared:[]};
const state:Save=(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}})();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`<div class="shell"><div class="game-frame"><div class="hud"><div class="hud-top"><div class="logo">MINE<span>DOZER</span></div><div class="coins"><span class="coin">$</span><span id="coins">0</span></div></div><div class="quarry-card"><b id="levelTitle"></b><small id="levelName"></small></div></div><div class="level-bar" id="levelBar"></div><div class="toast" id="toast">CLEAR THE QUARRY</div><div class="garage"><button class="upgrade" data-u="power"><span class="uicon">⚙️</span><b>ENGINE</b><span class="level" id="powerLevel"></span><span class="price" id="powerCost"></span></button><button class="upgrade" data-u="speed"><span class="uicon">🏎️</span><b>SPEED</b><span class="level" id="speedLevel"></span><span class="price" id="speedCost"></span></button><button class="upgrade" data-u="value"><span class="uicon">⚒️</span><b>CRUSHER</b><span class="level" id="valueLevel"></span><span class="price" id="valueCost"></span></button><button class="upgrade" data-u="scoop"><span class="uicon">🪣</span><b>SCOOP</b><span class="level" id="scoopLevel"></span><span class="price" id="scoopCost"></span></button></div><div class="controls"><div class="joystick" id="joystick"><div class="stick" id="stick"></div></div><button class="boost" id="boost">BOOST</button></div><div id="game"></div></div></div>`;
const $=<T extends HTMLElement>(q:string)=>document.querySelector<T>(q)!;
const toast=$<HTMLDivElement>('#toast');
let scene:Quarry|undefined;
const baseCosts:Record<Upgrade,number>={power:25,speed:30,value:40,scoop:55};
const cost=(k:Upgrade)=>Math.floor(baseCosts[k]*Math.pow(1.65,state[k]-1));
function say(t:string){toast.textContent=t;toast.animate([{transform:'translate(-50%,-7px)',opacity:.2},{transform:'translate(-50%,0)',opacity:1}],{duration:220})}
function syncUI(){
 $('#coins').textContent=Math.floor(state.coins).toLocaleString();
 $('#levelTitle').textContent=LEVELS[state.current].name.toUpperCase();
 $('#levelName').textContent=`LEVEL ${state.current+1} • ${scene?.remaining()??LEVELS[state.current].count} LOADS LEFT`;
 (['power','speed','value','scoop'] as Upgrade[]).forEach(k=>{$(`#${k}Level`).textContent=`LV. ${state[k]}`;$(`#${k}Cost`).textContent=`🪙 ${cost(k).toLocaleString()}`});
 const bar=$('#levelBar');bar.innerHTML='';LEVELS.forEach((l,i)=>{const b=document.createElement('button');b.className='level-btn'+(i===state.current?' active':'');b.textContent=i<=state.unlocked?`${i+1}`:`🔒 ${l.unlock}`;b.title=l.name;b.onclick=()=>selectLevel(i);bar.appendChild(b)});save();
}
function selectLevel(i:number){if(i>state.unlocked){const p=LEVELS[i].unlock;if(i!==state.unlocked+1){say('UNLOCK LEVELS IN ORDER');return}if(state.coins<p){say(`NEED ${p-Math.floor(state.coins)} MORE COINS`);return}state.coins-=p;state.unlocked=i;say(`${LEVELS[i].name.toUpperCase()} UNLOCKED!`)}state.current=i;save();scene?.scene.restart();syncUI()}
document.querySelectorAll<HTMLButtonElement>('.upgrade').forEach(btn=>btn.onclick=()=>{const k=btn.dataset.u as Upgrade,p=cost(k);if(state.coins<p){say(`NEED ${p-Math.floor(state.coins)} MORE COINS`);return}state.coins-=p;state[k]++;syncUI();scene?.applyScoop();scene?.flashUpgrade(k);say(`${k.toUpperCase()} UPGRADED!`)});

const input={x:0,y:0,boost:false};const joy=$<HTMLDivElement>('#joystick'),stick=$<HTMLDivElement>('#stick');let joyId:number|null=null;
function moveJoy(e:PointerEvent){const r=joy.getBoundingClientRect();let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;const m=Math.hypot(x,y),lim=34;if(m>lim){x=x/m*lim;y=y/m*lim}input.x=x/lim;input.y=y/lim;stick.style.transform=`translate(${x}px,${y}px)`}
joy.onpointerdown=e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e)};joy.onpointermove=e=>{if(e.pointerId===joyId)moveJoy(e)};const stop=(e:PointerEvent)=>{if(e.pointerId!==joyId)return;joyId=null;input.x=input.y=0;stick.style.transform='translate(0,0)'};joy.onpointerup=stop;joy.onpointercancel=stop;const boost=$<HTMLButtonElement>('#boost');boost.onpointerdown=()=>input.boost=true;boost.onpointerup=boost.onpointercancel=()=>input.boost=false;

class Quarry extends Phaser.Scene{
 player!:Phaser.Physics.Arcade.Image;rocks!:Phaser.Physics.Arcade.Group;crusher!:Phaser.GameObjects.Zone;cursors!:Phaser.Types.Input.Keyboard.CursorKeys;keys!:Record<string,Phaser.Input.Keyboard.Key>;dustTimer=0;crusherGlow!:Phaser.GameObjects.Rectangle;
 create(){scene=this;const w=520,h=940,l=LEVELS[state.current];this.cameras.main.setBackgroundColor(l.ground);this.drawWorld(w,h,l);this.makeTextures();this.drawCrusher(w);this.player=this.physics.add.image(w/2,760,'dozer').setCollideWorldBounds(true).setDrag(900).setDepth(5);this.applyScoop();this.rocks=this.physics.add.group({collideWorldBounds:true});this.physics.add.collider(this.rocks,this.rocks);this.physics.add.collider(this.player,this.rocks,(_,o)=>{const r=o as Phaser.Physics.Arcade.Image;if(r.getData('crushing'))return;const b=r.body as Phaser.Physics.Arcade.Body,p=this.player.body.velocity,f=.36+state.power*.13+state.scoop*.05;b.velocity.x+=p.x*f;b.velocity.y+=p.y*f});this.physics.add.overlap(this.rocks,this.crusher,(_,o)=>this.crush(o as Phaser.Physics.Arcade.Image));this.cursors=this.input.keyboard!.createCursorKeys();this.keys=this.input.keyboard!.addKeys('W,A,S,D') as Record<string,Phaser.Input.Keyboard.Key>;for(let i=0;i<l.count;i++)this.spawnRock(i);syncUI();say(`CLEAR ${l.count} LOADS FROM ${l.name.toUpperCase()}`)}
 drawWorld(w:number,h:number,l:Level){const g=this.add.graphics();g.fillStyle(l.ground).fillRect(0,0,w,h);for(let y=190;y<h;y+=34){g.lineStyle(2,0x2d1b10,.12);g.lineBetween(88,y,432,y+Phaser.Math.Between(-5,5))}g.fillStyle(l.wall);for(let y=160;y<h;y+=55){g.fillRoundedRect(0,y,42+Phaser.Math.Between(0,18),48,12);g.fillRoundedRect(w-Phaser.Math.Between(42,60),y,60,48,12)}for(let i=0;i<70;i++){g.fillStyle(0xffffff,Phaser.Math.FloatBetween(.04,.15));g.fillCircle(Phaser.Math.Between(50,w-50),Phaser.Math.Between(185,h-100),Phaser.Math.Between(1,5))}for(let i=0;i<15;i++){const x=Math.random()<.5?Phaser.Math.Between(8,65):Phaser.Math.Between(w-65,w-8),y=Phaser.Math.Between(190,h-120);g.fillStyle(0x2f6d2d,.8).fillCircle(x,y,Phaser.Math.Between(5,11));g.fillStyle(0x75a948,.7).fillCircle(x+4,y-4,Phaser.Math.Between(3,7))}}
 drawCrusher(w:number){const g=this.add.graphics().setDepth(3);g.fillStyle(0x202525).fillRoundedRect(52,164,w-104,106,18);g.lineStyle(4,0x6d7371).strokeRoundedRect(52,164,w-104,106,18);g.fillStyle(0x111414).fillRect(92,204,w-184,48);for(let x=96;x<w-100;x+=26){g.fillStyle((x/26)%2?0xf6b51c:0x181818).fillTriangle(x,198,x+13,181,x+26,198)}for(let x=105;x<w-108;x+=34){g.fillStyle(0xb8b9b7).fillTriangle(x,210,x+17,246,x+34,210);g.fillStyle(0x5d6060).fillTriangle(x+7,210,x+17,235,x+27,210)}g.fillStyle(0x433020).fillRoundedRect(34,188,46,60,10).fillRoundedRect(w-80,188,46,60,10);g.fillStyle(0xff7c00).fillCircle(57,181,8).fillCircle(w-57,181,8);this.crusherGlow=this.add.rectangle(w/2,230,w-190,40,0xff7b00,.15).setDepth(2);this.tweens.add({targets:this.crusherGlow,alpha:{from:.08,to:.32},duration:500,yoyo:true,repeat:-1});this.crusher=this.add.zone(w/2,230,w-190,52);this.physics.add.existing(this.crusher,true);this.add.text(w/2,178,'ROCK CRUSHER',{fontSize:'18px',fontStyle:'bold',color:'#ffd14a',stroke:'#4c2600',strokeThickness:4}).setOrigin(.5).setDepth(4)}
 makeTextures(){if(this.textures.exists('dozer'))return;const d=this.add.graphics();d.fillStyle(0x17191a).fillRoundedRect(1,16,14,67,7).fillRoundedRect(73,16,14,67,7);d.fillStyle(0xf4ad19).fillRoundedRect(13,18,62,58,9);d.fillStyle(0xffca36).fillRoundedRect(23,4,42,35,8);d.fillStyle(0x18384b).fillRoundedRect(30,10,28,17,4);d.fillStyle(0x2b2520).fillRect(25,0,7,17).fillRect(57,0,7,17);d.fillStyle(0xe69300).fillRect(18,63,52,13);d.fillStyle(0xffc62b).fillTriangle(8,90,79,90,70,66).fillTriangle(8,90,18,66,70,66);d.lineStyle(3,0x7b4a00).strokeTriangle(8,90,79,90,70,66);d.generateTexture('dozer',88,92);d.destroy();const r=this.add.graphics();r.fillStyle(0x686b70).fillCircle(25,25,24);r.fillStyle(0x92969b).fillCircle(17,15,10);r.fillStyle(0x4c4f53).fillCircle(31,32,8);r.generateTexture('rock',50,50);r.clear();r.fillStyle(0xb8750c).fillCircle(28,28,27);r.fillStyle(0xffcf3b).fillCircle(19,17,11);r.fillStyle(0xe99e11).fillCircle(35,34,9);r.generateTexture('gold',56,56);r.clear();r.fillStyle(0x305b79).fillTriangle(30,2,8,58,52,58);r.fillStyle(0x73dcff).fillTriangle(30,5,23,53,40,53);r.fillStyle(0xc5f6ff).fillTriangle(30,5,30,45,40,53);r.generateTexture('crystal',60,60);r.destroy()}
 applyScoop(){if(!this.player?.body)return;const width=Math.min(126,58+state.scoop*10);this.player.setScale(1+Math.min(.28,(state.scoop-1)*.045));this.player.body.setSize(width,88,true)}
 flashUpgrade(k:Upgrade){if(!this.player)return;const color=k==='scoop'?0xffcf43:0xffffff;this.player.setTint(color);this.time.delayedCall(240,()=>this.player.clearTint())}
 remaining(){return this.rocks?.countActive(true)??LEVELS[state.current].count}
 spawnRock(i:number){const l=LEVELS[state.current],roll=Math.random();let key='rock',mult=1;if(roll<l.crystalChance){key='crystal';mult=3.3}else if(roll<l.crystalChance+l.goldChance){key='gold';mult=2.4}const cols=4,x=78+(i%cols)*122,y=330+Math.floor(i/cols)*82;const r=this.rocks.create(x+Phaser.Math.Between(-22,22),y+Phaser.Math.Between(-16,16),key) as Phaser.Physics.Arcade.Image;r.setCircle(key==='rock'?24:27).setDrag(350).setBounce(.06).setData('value',Math.round(l.rockValue*mult)).setData('crushing',false);r.setAngle(Phaser.Math.Between(-18,18));r.setScale(Phaser.Math.FloatBetween(.88,1.08))}
 crush(r:Phaser.Physics.Arcade.Image){if(!r.active||r.getData('crushing'))return;r.setData('crushing',true);(r.body as Phaser.Physics.Arcade.Body).enable=false;const payout=Math.round((r.getData('value') as number)*(1+(state.value-1)*.28));state.coins+=payout;state.earned+=payout;syncUI();for(let i=0;i<9;i++){const p=this.add.circle(r.x,r.y,Phaser.Math.Between(2,5),i%3===0?0xffbe27:0xc4c4c4).setDepth(8);this.tweens.add({targets:p,x:r.x+Phaser.Math.Between(-55,55),y:r.y+Phaser.Math.Between(-30,30),alpha:0,duration:Phaser.Math.Between(300,550),onComplete:()=>p.destroy()})}this.tweens.add({targets:r,scale:0,angle:220,duration:180,onComplete:()=>{r.destroy();syncUI();if(this.remaining()===0)this.completeLevel()}});const t=this.add.text(r.x,r.y,`+${payout}`,{fontSize:'25px',fontStyle:'bold',color:'#ffe15c',stroke:'#6a3900',strokeThickness:5}).setOrigin(.5).setDepth(9);this.tweens.add({targets:t,y:r.y-62,alpha:0,scale:1.2,duration:750,onComplete:()=>t.destroy()});this.cameras.main.shake(90,.0045);this.crusherGlow.setAlpha(.75);this.time.delayedCall(100,()=>this.crusherGlow.setAlpha(.2))}
 completeLevel(){if(!state.cleared.includes(state.current))state.cleared.push(state.current);save();const next=state.current+1;if(next<LEVELS.length&&next>state.unlocked)say(`QUARRY CLEAR! UNLOCK ${LEVELS[next].name.toUpperCase()} FOR ${LEVELS[next].unlock}`);else say('QUARRY CLEARED!')}
 update(_:number,delta:number){let x=input.x,y=input.y;if(this.cursors.left.isDown||this.keys.A.isDown)x=-1;if(this.cursors.right.isDown||this.keys.D.isDown)x=1;if(this.cursors.up.isDown||this.keys.W.isDown)y=-1;if(this.cursors.down.isDown||this.keys.S.isDown)y=1;const moving=Math.abs(x)+Math.abs(y)>.1,len=Math.hypot(x,y)||1,speed=(125+state.speed*18)*(input.boost?1.65:1);this.player.setVelocity(x/len*speed,y/len*speed);if(moving)this.player.setRotation(Math.atan2(y,x)+Math.PI/2);this.dustTimer+=delta;if(moving&&this.dustTimer>110){this.dustTimer=0;const p=this.add.circle(this.player.x,this.player.y+15,Phaser.Math.Between(3,7),0xd7b68a,.45).setDepth(2);this.tweens.add({targets:p,scale:2,alpha:0,duration:430,onComplete:()=>p.destroy()})}}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:520,height:940,backgroundColor:'#6c4a2b',physics:{default:'arcade',arcade:{gravity:{x:0,y:0},debug:false}},scene:[Quarry],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
