import Phaser from 'phaser';
import './style.css';

type Upgrade = 'power' | 'speed' | 'value' | 'scoop';
type Save = { coins:number; earned:number; power:number; speed:number; value:number; scoop:number; unlocked:number; current:number; cleared:number[] };
type Level = { name:string; count:number; unlock:number; rockValue:number; goldChance:number; crystalChance:number; ground:number; wall:number };

const VIEW_W=520, VIEW_H=940, WORLD_W=1100, WORLD_H=1800, CRUSHER_X=WORLD_W/2, CRUSHER_Y=210;
const MIN_MINEABLES=5, REPLENISH_BATCH=5;
const LEVELS:Level[]=[
  {name:'Gravel Pit',count:10,unlock:0,rockValue:5,goldChance:0,crystalChance:0,ground:0x8a5b32,wall:0x51351f},
  {name:'Granite Cut',count:14,unlock:50,rockValue:11,goldChance:.12,crystalChance:0,ground:0x686765,wall:0x3f4245},
  {name:'Gold Ridge',count:18,unlock:400,rockValue:22,goldChance:.30,crystalChance:.03,ground:0x81552d,wall:0x56361e},
  {name:'Crystal Basin',count:22,unlock:1100,rockValue:45,goldChance:.20,crystalChance:.30,ground:0x466f77,wall:0x29444d}
];
const KEY='mine-dozer-save-v2';
const defaults:Save={coins:0,earned:0,power:1,speed:1,value:1,scoop:1,unlocked:0,current:0,cleared:[]};
const state:Save=(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}})();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`<div class="shell"><div class="game-frame"><div class="hud"><div class="hud-top"><div class="logo">MINE<span>DOZER</span></div><div class="coins"><span class="coin">$</span><span id="coins">0</span></div></div><div class="quarry-card"><b id="levelTitle"></b><small id="levelName"></small></div></div><div class="level-bar" id="levelBar"></div><div class="toast" id="toast">MINE THE QUARRY</div><div class="garage"><button class="upgrade" data-u="power"><span class="uicon">⚙️</span><b>ENGINE</b><span class="level" id="powerLevel"></span><span class="price" id="powerCost"></span></button><button class="upgrade" data-u="speed"><span class="uicon">🏎️</span><b>SPEED</b><span class="level" id="speedLevel"></span><span class="price" id="speedCost"></span></button><button class="upgrade" data-u="value"><span class="uicon">⚒️</span><b>CRUSHER</b><span class="level" id="valueLevel"></span><span class="price" id="valueCost"></span></button><button class="upgrade" data-u="scoop"><span class="uicon">🪣</span><b>SCOOP</b><span class="level" id="scoopLevel"></span><span class="price" id="scoopCost"></span></button></div><div class="controls"><div class="joystick" id="joystick"><div class="stick" id="stick"></div></div><button class="boost" id="boost">BOOST</button></div><div id="game"></div></div></div>`;

const $=<T extends HTMLElement>(q:string)=>document.querySelector<T>(q)!;
const toast=$<HTMLDivElement>('#toast');
let scene:Quarry|undefined;
const baseCosts:Record<Upgrade,number>={power:25,speed:30,value:40,scoop:55};
const cost=(k:Upgrade)=>Math.floor(baseCosts[k]*Math.pow(1.65,state[k]-1));
function say(t:string){toast.textContent=t;toast.animate([{transform:'translate(-50%,-7px)',opacity:.2},{transform:'translate(-50%,0)',opacity:1}],{duration:220})}
function syncUI(){
  $('#coins').textContent=Math.floor(state.coins).toLocaleString();
  $('#levelTitle').textContent=LEVELS[state.current].name.toUpperCase();
  $('#levelName').textContent=scene?.statusText()??`LEVEL ${state.current+1}`;
  (['power','speed','value','scoop'] as Upgrade[]).forEach(k=>{$(`#${k}Level`).textContent=`LV. ${state[k]}`;$(`#${k}Cost`).textContent=`🪙 ${cost(k).toLocaleString()}`});
  const bar=$('#levelBar');bar.innerHTML='';LEVELS.forEach((l,i)=>{const b=document.createElement('button');b.className='level-btn'+(i===state.current?' active':'');b.textContent=i<=state.unlocked?`${i+1}`:`🔒 ${l.unlock}`;b.title=l.name;b.onclick=()=>selectLevel(i);bar.appendChild(b)});save();
}
function selectLevel(i:number){if(i>state.unlocked){const p=LEVELS[i].unlock;if(i!==state.unlocked+1){say('UNLOCK LEVELS IN ORDER');return}if(state.coins<p){say(`NEED ${p-Math.floor(state.coins)} MORE COINS`);return}state.coins-=p;state.unlocked=i;say(`${LEVELS[i].name.toUpperCase()} UNLOCKED!`)}state.current=i;save();scene?.scene.restart();syncUI()}
document.querySelectorAll<HTMLButtonElement>('.upgrade').forEach(btn=>btn.onclick=()=>{const k=btn.dataset.u as Upgrade,p=cost(k);if(state.coins<p){say(`NEED ${p-Math.floor(state.coins)} MORE COINS`);return}state.coins-=p;state[k]++;syncUI();scene?.applyScoop();scene?.flashUpgrade(k);say(`${k.toUpperCase()} UPGRADED!`)});

const input={x:0,y:0,boost:false}, joy=$<HTMLDivElement>('#joystick'), stick=$<HTMLDivElement>('#stick');let joyId:number|null=null;
function moveJoy(e:PointerEvent){const r=joy.getBoundingClientRect();let x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;const m=Math.hypot(x,y),lim=34;if(m>lim){x=x/m*lim;y=y/m*lim}input.x=x/lim;input.y=y/lim;stick.style.transform=`translate(${x}px,${y}px)`}
joy.onpointerdown=e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e)};joy.onpointermove=e=>{if(e.pointerId===joyId)moveJoy(e)};const stop=(e:PointerEvent)=>{if(e.pointerId!==joyId)return;joyId=null;input.x=input.y=0;stick.style.transform='translate(0,0)'};joy.onpointerup=stop;joy.onpointercancel=stop;const boost=$<HTMLButtonElement>('#boost');boost.onpointerdown=()=>input.boost=true;boost.onpointerup=boost.onpointercancel=()=>input.boost=false;

class Quarry extends Phaser.Scene{
  player!:Phaser.Physics.Arcade.Image;rocks!:Phaser.Physics.Arcade.Group;crusher!:Phaser.GameObjects.Zone;cursors!:Phaser.Types.Input.Keyboard.CursorKeys;keys!:Record<string,Phaser.Input.Keyboard.Key>;dustTimer=0;replenishTimer=0;crusherGlow!:Phaser.GameObjects.Rectangle;processed=0;quotaAnnounced=false;combo=0;comboUntil=0;loadsSinceChest=0;nextChestAt=10;
  create(){scene=this;const l=LEVELS[state.current];this.processed=0;this.quotaAnnounced=false;this.combo=0;this.loadsSinceChest=0;this.nextChestAt=Phaser.Math.Between(8,14);this.physics.world.setBounds(0,0,WORLD_W,WORLD_H);this.cameras.main.setBounds(0,0,WORLD_W,WORLD_H);this.cameras.main.setBackgroundColor(l.ground);this.drawWorld(l);this.makeTextures();this.drawCrusher();this.player=this.physics.add.image(WORLD_W/2,WORLD_H-180,'dozer').setCollideWorldBounds(true).setDrag(900).setDepth(5);this.applyScoop();this.cameras.main.startFollow(this.player,true,.12,.12);this.cameras.main.setDeadzone(150,220);this.rocks=this.physics.add.group({collideWorldBounds:true});this.physics.add.collider(this.rocks,this.rocks);this.physics.add.collider(this.player,this.rocks,(_,o)=>{const r=o as Phaser.Physics.Arcade.Image;if(r.getData('crushing'))return;const b=r.body as Phaser.Physics.Arcade.Body,p=this.player.body.velocity,f=.34+state.power*.13+state.scoop*.05;b.velocity.x+=p.x*f;b.velocity.y+=p.y*f});this.physics.add.overlap(this.rocks,this.crusher,(_,o)=>this.crush(o as Phaser.Physics.Arcade.Image));this.cursors=this.input.keyboard!.createCursorKeys();this.keys=this.input.keyboard!.addKeys('W,A,S,D') as Record<string,Phaser.Input.Keyboard.Key>;this.spawnPiles(l.count);if(Math.random()<.22)this.spawnChest();syncUI();say(`MINE ${l.count} LOADS TO COMPLETE THE QUOTA`)}
  drawWorld(l:Level){const g=this.add.graphics();g.fillStyle(l.ground).fillRect(0,0,WORLD_W,WORLD_H);for(let y=80;y<WORLD_H;y+=44){g.lineStyle(2,0x2d1b10,.10);g.lineBetween(100,y,WORLD_W-100,y+Phaser.Math.Between(-6,6))}g.fillStyle(l.wall);for(let y=0;y<WORLD_H;y+=64){g.fillRoundedRect(0,y,65+Phaser.Math.Between(0,30),56,14);g.fillRoundedRect(WORLD_W-Phaser.Math.Between(65,95),y,95,56,14)}for(let i=0;i<190;i++){g.fillStyle(0xffffff,Phaser.Math.FloatBetween(.035,.13));g.fillCircle(Phaser.Math.Between(90,WORLD_W-90),Phaser.Math.Between(80,WORLD_H-80),Phaser.Math.Between(1,5))}for(let i=0;i<38;i++){const x=Math.random()<.5?Phaser.Math.Between(12,90):Phaser.Math.Between(WORLD_W-90,WORLD_W-12),y=Phaser.Math.Between(120,WORLD_H-120);g.fillStyle(0x2f6d2d,.8).fillCircle(x,y,Phaser.Math.Between(6,13));g.fillStyle(0x75a948,.7).fillCircle(x+5,y-5,Phaser.Math.Between(3,8))}}
  drawCrusher(){const g=this.add.graphics().setDepth(3),x=CRUSHER_X-220,y=110,w=440;g.fillStyle(0x202525).fillRoundedRect(x,y,w,128,20);g.lineStyle(5,0x6d7371).strokeRoundedRect(x,y,w,128,20);g.fillStyle(0x111414).fillRect(x+45,y+50,w-90,58);for(let tx=x+50;tx<x+w-50;tx+=30)g.fillStyle((tx/30)%2?0xf6b51c:0x181818).fillTriangle(tx,y+44,tx+15,y+23,tx+30,y+44);for(let tx=x+58;tx<x+w-58;tx+=38){g.fillStyle(0xb8b9b7).fillTriangle(tx,y+60,tx+19,y+105,tx+38,y+60);g.fillStyle(0x5d6060).fillTriangle(tx+8,y+60,tx+19,y+92,tx+30,y+60)}g.fillStyle(0x433020).fillRoundedRect(x-28,y+30,54,72,12).fillRoundedRect(x+w-26,y+30,54,72,12);g.fillStyle(0xff7c00).fillCircle(x-2,y+24,9).fillCircle(x+w+2,y+24,9);this.crusherGlow=this.add.rectangle(CRUSHER_X,CRUSHER_Y,330,48,0xff7b00,.15).setDepth(2);this.tweens.add({targets:this.crusherGlow,alpha:{from:.08,to:.32},duration:500,yoyo:true,repeat:-1});this.crusher=this.add.zone(CRUSHER_X,CRUSHER_Y,340,62);this.physics.add.existing(this.crusher,true);this.add.text(CRUSHER_X,y+20,'ROCK CRUSHER',{fontSize:'20px',fontStyle:'bold',color:'#ffd14a',stroke:'#4c2600',strokeThickness:4}).setOrigin(.5).setDepth(4)}
  makeTextures(){if(this.textures.exists('dozer'))return;const d=this.add.graphics();d.fillStyle(0x17191a).fillRoundedRect(1,16,14,67,7).fillRoundedRect(73,16,14,67,7);d.fillStyle(0xf4ad19).fillRoundedRect(13,18,62,58,9);d.fillStyle(0xffca36).fillRoundedRect(23,4,42,35,8);d.fillStyle(0x18384b).fillRoundedRect(30,10,28,17,4);d.fillStyle(0x2b2520).fillRect(25,0,7,17).fillRect(57,0,7,17);d.fillStyle(0xe69300).fillRect(18,63,52,13);d.fillStyle(0xffc62b).fillTriangle(8,90,79,90,70,66).fillTriangle(8,90,18,66,70,66);d.lineStyle(3,0x7b4a00).strokeTriangle(8,90,79,90,70,66);d.generateTexture('dozer',88,92);d.destroy();const r=this.add.graphics();r.fillStyle(0x686b70).fillCircle(15,15,14);r.fillStyle(0x92969b).fillCircle(10,9,6);r.fillStyle(0x4c4f53).fillCircle(19,20,5);r.generateTexture('rock',30,30);r.clear();r.fillStyle(0xb8750c).fillCircle(16,16,15);r.fillStyle(0xffcf3b).fillCircle(11,9,6);r.fillStyle(0xe99e11).fillCircle(21,21,5);r.generateTexture('gold',32,32);r.clear();r.fillStyle(0x305b79).fillTriangle(17,1,4,33,30,33);r.fillStyle(0x73dcff).fillTriangle(17,3,13,29,23,29);r.fillStyle(0xc5f6ff).fillTriangle(17,3,17,25,23,29);r.generateTexture('crystal',34,34);r.clear();r.fillStyle(0x3a210f).fillRoundedRect(2,10,42,28,5);r.fillStyle(0x9b521f).fillRoundedRect(3,2,40,18,7);r.fillStyle(0xffc62b).fillRect(5,16,36,5).fillRect(18,2,8,36);r.fillStyle(0x6b360f).fillRect(5,22,36,13);r.fillStyle(0xffdc55).fillRoundedRect(18,20,9,11,2);r.fillStyle(0x2a180b).fillCircle(22.5,25,2);r.generateTexture('chest',46,40);r.destroy()}
  applyScoop(){if(!this.player?.body)return;const width=Math.min(126,58+state.scoop*10);this.player.setScale(1+Math.min(.28,(state.scoop-1)*.045));this.player.body.setSize(width,88,true)}
  flashUpgrade(k:Upgrade){if(!this.player)return;this.player.setTint(k==='scoop'?0xffcf43:0xffffff);this.time.delayedCall(240,()=>this.player.clearTint())}
  mineableCount(){let count=0;this.rocks?.children.iterate(o=>{const r=o as Phaser.Physics.Arcade.Image;if(r.active&&!r.getData('crushing')&&r.getData('kind')!=='chest')count++});return count}
  chestCount(){let count=0;this.rocks?.children.iterate(o=>{const r=o as Phaser.Physics.Arcade.Image;if(r.active&&!r.getData('crushing')&&r.getData('kind')==='chest')count++});return count}
  statusText(){const quota=Math.min(this.processed,LEVELS[state.current].count);return `LEVEL ${state.current+1} • QUOTA ${quota}/${LEVELS[state.current].count} • ${this.mineableCount()} ACTIVE`}
  spawnPiles(count:number){const centers=[{x:230,y:760},{x:840,y:720},{x:290,y:1250},{x:790,y:1320},{x:550,y:1540}];for(let i=0;i<count;i++){const p=centers[i%centers.length],ring=Math.floor(i/centers.length);this.spawnRock(p.x+Phaser.Math.Between(-55,55)+ring*14,p.y+Phaser.Math.Between(-45,45)+ring*10)}}
  spawnDepositBatch(count=REPLENISH_BATCH){const centers=[{x:190,y:650},{x:890,y:650},{x:250,y:980},{x:850,y:1060},{x:220,y:1420},{x:850,y:1450},{x:550,y:1640}];const p=Phaser.Utils.Array.GetRandom(centers);for(let i=0;i<count;i++)this.spawnRock(p.x+Phaser.Math.Between(-70,70),p.y+Phaser.Math.Between(-55,55));syncUI();say(`NEW DEPOSIT DISCOVERED • +${count} LOADS`)}
  spawnRock(x:number,y:number){const l=LEVELS[state.current],roll=Math.random();let key='rock',mult=1;if(roll<l.crystalChance){key='crystal';mult=3.3}else if(roll<l.crystalChance+l.goldChance){key='gold';mult=2.4}const r=this.rocks.create(x,y,key) as Phaser.Physics.Arcade.Image;r.setCircle(key==='rock'?14:15).setDrag(390).setBounce(.04).setData('kind','ore').setData('value',Math.round(l.rockValue*mult)).setData('crushing',false);r.setAngle(Phaser.Math.Between(-18,18)).setScale(Phaser.Math.FloatBetween(.82,1.02))}
  spawnChest(){if(this.chestCount()>0)return;const spots=[{x:170,y:820},{x:920,y:830},{x:180,y:1320},{x:920,y:1320},{x:550,y:1580}],p=Phaser.Utils.Array.GetRandom(spots);const c=this.rocks.create(p.x+Phaser.Math.Between(-35,35),p.y+Phaser.Math.Between(-35,35),'chest') as Phaser.Physics.Arcade.Image;c.setSize(40,34,true).setDrag(470).setBounce(.03).setDepth(4).setData('kind','chest').setData('crushing',false);this.tweens.add({targets:c,angle:{from:-4,to:4},duration:520,yoyo:true,repeat:-1});const ring=this.add.circle(c.x,c.y,34,0xffd84a,.15).setStrokeStyle(3,0xffe86b,.75).setDepth(2);this.tweens.add({targets:ring,scale:{from:.8,to:1.35},alpha:{from:.65,to:0},duration:900,repeat:-1});c.setData('ring',ring);say('TREASURE CHEST DISCOVERED!')}
  crush(r:Phaser.Physics.Arcade.Image){if(!r.active||r.getData('crushing'))return;r.setData('crushing',true);(r.body as Phaser.Physics.Arcade.Body).enable=false;if(r.getData('kind')==='chest'){this.openChest(r);return}const now=this.time.now;this.combo=now<this.comboUntil?Math.min(5,this.combo+1):1;this.comboUntil=now+4000;const base=Math.round((r.getData('value') as number)*(1+(state.value-1)*.28));const payout=Math.round(base*(1+(this.combo-1)*.15));state.coins+=payout;state.earned+=payout;this.processed++;this.loadsSinceChest++;syncUI();for(let i=0;i<7;i++){const p=this.add.circle(r.x,r.y,Phaser.Math.Between(2,4),i%3===0?0xffbe27:0xc4c4c4).setDepth(8);this.tweens.add({targets:p,x:r.x+Phaser.Math.Between(-45,45),y:r.y+Phaser.Math.Between(-25,25),alpha:0,duration:Phaser.Math.Between(260,480),onComplete:()=>p.destroy()})}this.tweens.add({targets:r,scale:0,angle:220,duration:180,onComplete:()=>{r.destroy();syncUI();this.checkQuota();if(this.loadsSinceChest>=this.nextChestAt&&this.chestCount()===0){this.loadsSinceChest=0;this.nextChestAt=Phaser.Math.Between(10,18);this.time.delayedCall(650,()=>this.spawnChest())}}});const comboText=this.combo>1?`  x${this.combo} COMBO`:'';const t=this.add.text(r.x,r.y,`+${payout}${comboText}`,{fontSize:this.combo>1?'20px':'24px',fontStyle:'bold',color:'#ffe15c',stroke:'#6a3900',strokeThickness:5}).setOrigin(.5).setDepth(9);this.tweens.add({targets:t,y:r.y-58,alpha:0,scale:1.15,duration:720,onComplete:()=>t.destroy()});this.cameras.main.shake(90,.0045);this.crusherGlow.setAlpha(.75);this.time.delayedCall(100,()=>this.crusherGlow.setAlpha(.2))}
  openChest(chest:Phaser.Physics.Arcade.Image){const ring=chest.getData('ring') as Phaser.GameObjects.Arc|undefined;ring?.destroy();const upgrades:Upgrade[]=['power','speed','value','scoop'];const upgradeReward=Math.random()<.32;let label='';if(upgradeReward){const k=Phaser.Utils.Array.GetRandom(upgrades);state[k]++;label=`FREE ${k.toUpperCase()} UPGRADE!`;this.applyScoop();this.flashUpgrade(k)}else{const min=180+state.current*120,max=420+state.current*260,coins=Phaser.Math.Between(min,max);state.coins+=coins;state.earned+=coins;label=`+${coins} BONUS COINS!`}save();syncUI();for(let i=0;i<18;i++){const color=i%3===0?0xffe75a:i%3===1?0xff9e19:0xffffff;const p=this.add.circle(chest.x,chest.y,Phaser.Math.Between(2,6),color).setDepth(10);this.tweens.add({targets:p,x:chest.x+Phaser.Math.Between(-105,105),y:chest.y+Phaser.Math.Between(-85,60),alpha:0,scale:Phaser.Math.FloatBetween(.6,1.8),duration:Phaser.Math.Between(500,900),onComplete:()=>p.destroy()})}const t=this.add.text(chest.x,chest.y,label,{fontSize:'25px',fontStyle:'bold',align:'center',color:'#fff17a',stroke:'#6b3500',strokeThickness:6}).setOrigin(.5).setDepth(12);this.tweens.add({targets:t,y:chest.y-90,scale:1.2,duration:500,ease:'Back.Out',hold:700,alpha:0,onComplete:()=>t.destroy()});this.tweens.add({targets:chest,scale:0,angle:360,duration:280,onComplete:()=>chest.destroy()});this.cameras.main.shake(220,.009);this.crusherGlow.setAlpha(1);this.time.delayedCall(180,()=>this.crusherGlow.setAlpha(.2));say(`CHEST OPENED • ${label}`)}
  checkQuota(){const target=LEVELS[state.current].count;if(this.quotaAnnounced||this.processed<target)return;this.quotaAnnounced=true;if(!state.cleared.includes(state.current))state.cleared.push(state.current);const bonus=100*(state.current+1);state.coins+=bonus;state.earned+=bonus;save();syncUI();say(`QUOTA COMPLETE! +${bonus} COINS • MINING CONTINUES`)}
  update(_:number,delta:number){let x=input.x,y=input.y;if(this.cursors.left.isDown||this.keys.A.isDown)x=-1;if(this.cursors.right.isDown||this.keys.D.isDown)x=1;if(this.cursors.up.isDown||this.keys.W.isDown)y=-1;if(this.cursors.down.isDown||this.keys.S.isDown)y=1;const moving=Math.abs(x)+Math.abs(y)>.1,len=Math.hypot(x,y)||1,speed=(125+state.speed*18)*(input.boost?1.65:1);this.player.setVelocity(x/len*speed,y/len*speed);if(moving)this.player.setRotation(Math.atan2(y,x)+Math.PI/2);this.dustTimer+=delta;if(moving&&this.dustTimer>110){this.dustTimer=0;const p=this.add.circle(this.player.x,this.player.y+15,Phaser.Math.Between(3,7),0xd7b68a,.45).setDepth(2);this.tweens.add({targets:p,scale:2,alpha:0,duration:430,onComplete:()=>p.destroy()})}this.replenishTimer+=delta;if(this.replenishTimer>900){this.replenishTimer=0;if(this.mineableCount()<MIN_MINEABLES)this.spawnDepositBatch(REPLENISH_BATCH)}}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:VIEW_W,height:VIEW_H,backgroundColor:'#6c4a2b',physics:{default:'arcade',arcade:{gravity:{x:0,y:0},debug:false}},scene:[Quarry],scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH}});
